services:
  mongoredisapi:
    image: ${DOCKER_REGISTRY-}mongoredisapi
    container_name: api
    build:
      context: .
      dockerfile: MongoRedisApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mongo
      - mongo-express
      - redis
  
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.containers/mongo-db:/var/lib/mongodb/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: 123456
      REDIS_PORT: 6379
      REDIS_DATABASES: 4
